# Generated by Django 6.0.3 on 2026-03-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity_female',
            field=models.PositiveIntegerField(blank=True, help_text='Max female spots. Defaults to capacity / 2.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity_male',
            field=models.PositiveIntegerField(blank=True, help_text='Max male spots. Defaults to capacity / 2.', null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waitlisted', 'Waitlisted'), ('confirmed', 'Confirmed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
