# Generated by Django 6.0.3 on 2026-03-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_capacity_female_event_capacity_male_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='capacity_female',
        ),
        migrations.RemoveField(
            model_name='event',
            name='capacity_male',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='max_male_ratio',
            field=models.FloatField(default=0.5, help_text='Maximum fraction of reserved spots that can be male (e.g. 0.5 = 50%).'),
        ),
    ]
