# Generated by Django 6.0.3 on 2026-03-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_event_capacity_female_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='contact_preference',
        ),
        migrations.RemoveField(
            model_name='event',
            name='age_group',
        ),
        migrations.AddField(
            model_name='attendee',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='max_age',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='event',
            name='min_age',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_male_ratio',
            field=models.FloatField(default=0.55, help_text='Maximum fraction of reserved spots that can be male (e.g. 0.5 = 50%).'),
        ),
    ]
