# Generated by Django 6.0.3 on 2026-03-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_attendee_age_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for no upper limit.', null=True),
        ),
    ]
