# Generated by Django 6.0.3 on 2026-03-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_max_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='experience',
            field=models.CharField(choices=[('none', 'Never played'), ('beginner', 'Beginner (played a few times)'), ('intermediate', 'Intermediate (play regularly)'), ('advanced', 'Advanced (competitive)')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='attending_coaching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='attending_happy_hour',
            field=models.BooleanField(default=False),
        ),
    ]
