# Generated by Django 6.0.3 on 2026-03-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_attendee_experience_registration_attending_coaching_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
