# Generated by Django 6.0.3 on 2026-03-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_event_status_alter_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='payment_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
