# Generated by Django 6.0.3 on 2026-03-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_payment_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emaillog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
